# Generated by Django 5.2.9 on 2025-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_merge_20251216_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogsys',
            name='name_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
