# Generated by Django 5.2.9 on 2025-12-16 22:11

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_foodlogsys_is_consumed_foodlogusage'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlogusage',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterField(
            model_name='foodlogsys',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='foodlogusage',
            name='used_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='foodlogusage',
            index=models.Index(fields=['user', 'used_at'], name='food_foodlo_user_id_a6cd09_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlogusage',
            index=models.Index(fields=['recipe'], name='food_foodlo_recipe__078a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='foodlogusage',
            index=models.Index(fields=['foodlog'], name='food_foodlo_foodlog_d801a2_idx'),
        ),
    ]
