# Generated by Django 5.2.9 on 2025-12-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodlogsys_name_normalized'),
        ('food', '0007_alter_foodcomrecipe_options_and_more'),
    ]

    operations = [
    ]
