# Generated by Django 5.2.9 on 2025-12-19 17:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_merge_20251219_1718'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogsys',
            name='is_consumed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='foodlogsys',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='FoodLogUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('foodlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodlogsys')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.mealdbrecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='food_foodlo_user_id_a6cd09_idx'), models.Index(fields=['recipe'], name='food_foodlo_recipe__078a6d_idx'), models.Index(fields=['foodlog'], name='food_foodlo_foodlog_d801a2_idx')],
            },
        ),
    ]
