# Generated by Django 5.2.9 on 2025-12-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplanmeal',
            options={'ordering': ['meal_plan_day__date', 'meal_time'], 'verbose_name': 'Meal Plan Meal', 'verbose_name_plural': 'Meal Plan Meals'},
        ),
        migrations.AddIndex(
            model_name='mealplanday',
            index=models.Index(fields=['date', 'is_confirmed'], name='meal_plans__date_869862_idx'),
        ),
    ]
